[package]
name = "serpent"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]
edition = "2018"

[lib]
name = "serpent"
path = "src/lib.rs"

[[example]]
name = "transpile_simple"
path = "examples/transpile_simple.rs"

[[example]]
name = "transpile_black_scholes"
path = "examples/transpile_black_scholes.rs"

[dependencies]
# Python AST
rustpython-parser = { version = "0.1.1" }
# `num-bigint` "^0.2" matching with `rustpython-parser` "0.1.1"
num-bigint = "^0.2"

# Rust AST
syn = { version = "1.0.17", features = ["full", "clone-impls", "extra-traits", "printing", "parsing"] }
# `quote` "^1.0" matching with `syn` "1.0.17"
quote = "^1.0"
# `proc-macro2` "^1.0.7" matching with `syn` "1.0.17"
proc-macro2 = "^1.0.7"

derive_deref = "^1.1"
log = "^0.4"
pretty_env_logger = "^0.3"
rustfmt = "^0.10"
color-backtrace = "^0.3"
ctor = "0.1.14"
thiserror = "^1.0"

[dev-dependencies]
lazy_static = "^1.4"
sourcefile = "^0.1"
anyhow = "^1.0"
