[package]
name = "serpent"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]
edition = "2018"

[lib]
name = "serpent"
path = "src/lib.rs"

[[example]]
name = "transpile-simple"
path = "examples/transpile-simple.rs"

[dependencies]
# Python AST
rustpython-parser = { version = "0.1.1" }
# Rust AST
syn = { version = "1.0.17", features = ["full", "clone-impls"] }
derive_deref = "1.1.0"
# `quote` "^1.0" matching with `syn` "1.0.17"
quote = "^1.0"
# `num-bigint` "^0.2" matching with `rustpython-parser` "0.1.1"
num-bigint = "^0.2"
# `proc-macro2` "^1.0.7" matching with `syn` "1.0.17"
proc-macro2 = "^1.0.7"

[dev-dependencies]
sourcefile = "0.1.4"
